package test.selenium.DualCore.Boundary;
import org.junit.Test;
import org.junit.Before;
import org.hamcrest.CoreMatchers;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PilotModelTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void pilotModelTest() {
    driver.get("http://localhost:8080/FlightTrafficControlSystem/showPilotsAdmin.jsp");
    driver.manage().window().setSize(new Dimension(1120, 1220));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Edit")).click();
    vars.put("win2533", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2533").toString());
    driver.findElement(By.name("age")).click();
    driver.findElement(By.name("age")).sendKeys("30");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("new Pilot.")).click();
    vars.put("win3821", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3821").toString());
    driver.findElement(By.name("first_name")).click();
    driver.findElement(By.name("first_name")).sendKeys("henil");
    driver.findElement(By.name("last_name")).click();
    driver.findElement(By.name("last_name")).sendKeys("shah");
    driver.findElement(By.name("age")).click();
    driver.findElement(By.name("age")).sendKeys("20");
    driver.findElement(By.name("gender")).click();
    driver.findElement(By.name("gender")).sendKeys("Male");
    driver.findElement(By.name("nationality")).click();
    driver.findElement(By.name("nationality")).sendKeys("indian");
    driver.findElement(By.name("training_level")).click();
    driver.findElement(By.name("training_level")).sendKeys("99");
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("tr:nth-child(8) > td:nth-child(9) > a")).click();
    vars.put("win4677", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4677").toString());
  }
}
